### ISSUE TITLE
Is there a direct link to the data?

### ISSUE THREAD

**Issue by mrchrisadams** [anouchk/ETS_scraper#1]
Hi Ana!

Thanks for running the the workshop for this topic at Mozfest - would you let me know where I can download the assembled dataset that was used in workshop please?

When I follow the link below from the README page I end up on a 404 page:

https://www.data.gouv.fr/fr/datasets/donnees-2005-2016-du-marche-europeen-des-quotas-de-co2-ets/

**Comment by anouchk** [comment]
Hi Chris !
Thank for raising this issue : I changed the title of the dataset and... the link changed. Here is yhe good one :
https://www.data.gouv.fr/fr/datasets/donnees-2005-2016-du-marche-europeen-des-quotas-de-co2-ets-2005-2016-data-from-the-european-emissions-trading-scheme-ets/
I'll change the readme. Also if the same problem happens in the future, I guess the best is to go on data.gouv.fr and search for "ETS".
I might end up putting the dataset on github.
Kind wishes,
Ana

**Comment by anouchk** [comment]
README changed ! And repo created : https://github.com/anouchk/ETS_data
I hope it'll be easier now.
Thank you again Chris, ping me if I can do something else !
Ana
